# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      MAINTITLE: MasterThesis
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # Runs a set of commands using the runners shell
        # Previously used to install pdftotext
        # sudo apt-get install libpoppler-cpp-dev pkg-config
        # python -m pip install --upgrade pip
        # pip install pdftotext
    - name: Install pdftotext
      run: |
        sudo apt-get install poppler-utils
    - name: Check if the main PDF is attached to the push
      run: | 
        if [ -f "$MAINTITLE.pdf" ]; then
          echo "OKAY, $MAINTITLE.pdf is attached!"
        else
          echo "$MAINTITLE.pdf is missing. You should attach it!"
        fi
    - name: Count the number of words in the main PDF
      run: |
        words=$(pdftotext $MAINTITLE.pdf - | wc -w )
        echo Currently, $words words in $MAINTITLE.pdf💪
